import type { CardDefinition } from '../types/card.ts'

export const CARD_DATABASE: CardDefinition[] = [
  {
    definitionId: 'forest_guardian',
    name: 'Forest Guardian',
    type: 'creature',
    rarity: 'common',
    cost: 2,
    power: 2,
    toughness: 3,
    effects: [],
    description: 'A steadfast protector of the ancient woods.',
    imageUrl: '',
    keywords: ['taunt'],
  },
  {
    definitionId: 'fire_bolt',
    name: 'Fire Bolt',
    type: 'spell',
    rarity: 'common',
    cost: 1,
    effects: [{ type: 'damage', value: 3, target: 'creature' }],
    description: 'Deal 3 damage to any target.',
    imageUrl: '',
    keywords: [],
  },
  {
    definitionId: 'healing_touch',
    name: 'Healing Touch',
    type: 'spell',
    rarity: 'common',
    cost: 2,
    effects: [{ type: 'heal', value: 5, target: 'self' }],
    description: 'Restore 5 health.',
    imageUrl: '',
    keywords: [],
  },
  {
    definitionId: 'storm_drake',
    name: 'Storm Drake',
    type: 'creature',
    rarity: 'rare',
    cost: 4,
    power: 4,
    toughness: 3,
    effects: [{ type: 'damage', value: 1, target: 'opponent' }],
    description: 'When played, deal 1 damage to the opponent.',
    imageUrl: '',
    keywords: ['flying', 'haste'],
  },
  {
    definitionId: 'ancient_dragon',
    name: 'Ancient Dragon',
    type: 'creature',
    rarity: 'legendary',
    cost: 8,
    power: 8,
    toughness: 8,
    effects: [{ type: 'damage', value: 3, target: 'all_creatures' }],
    description: 'When played, deal 3 damage to all enemy creatures.',
    imageUrl: '',
    keywords: ['flying'],
  },
]
