import type { CardDefinition } from '../types/card.ts'

// Neutral cards — no affinity, any deck can include them
const NEUTRAL_CARDS: CardDefinition[] = [
  {
    definitionId: 'village_scout',
    name: 'Village Scout',
    type: 'unit',
    rarity: 'common',
    cost: 1,
    power: 1,
    keywords: [],
    affinity: [],
    description: 'A humble scout.',
    flavourText: 'Not every hero wears armour.',
    imageUrl: './cards/village-scout.png',
  },
  {
    definitionId: 'wandering_blade',
    name: 'Wandering Blade',
    type: 'unit',
    rarity: 'common',
    cost: 2,
    power: 2,
    keywords: ['challenger'],
    affinity: [],
    description: 'Challenger. Force an opponent\'s unit to contest this location.',
    flavourText: 'No lord, no banner — just steel and the road ahead.',
    imageUrl: './cards/wandering-blade.png',
  },
  {
    definitionId: 'shield_warden',
    name: 'Shield Warden',
    type: 'unit',
    rarity: 'uncommon',
    cost: 3,
    power: 3,
    keywords: ['resilient'],
    affinity: [],
    description: 'Resilient. Stays on the board between rounds.',
    flavourText: 'He has stood at this gate for forty years. He will stand for forty more.',
    imageUrl: './cards/shield-warden.png',
  },
  {
    definitionId: 'thunder_hawk',
    name: 'Thunder Hawk',
    type: 'unit',
    rarity: 'uncommon',
    cost: 4,
    power: 5,
    keywords: ['overwhelm'],
    affinity: [],
    description: 'Overwhelm. If this location\'s power exceeds the opponent\'s by 5+, gain +2 extra.',
    flavourText: 'The sky itself breaks before its wings.',
    imageUrl: './cards/thunder-hawk.png',
  },
]

// The Forge affinity — transformation payoffs, playing from strength
const FORGE_CARDS: CardDefinition[] = [
  {
    definitionId: 'iron_golem',
    name: 'Iron Golem',
    type: 'unit',
    rarity: 'common',
    cost: 3,
    power: 4,
    keywords: [],
    affinity: ['the_forge'],
    description: 'A steadfast construct built in the fires below.',
    flavourText: 'Forged without a heart, yet it fights as though it has something to protect.',
    imageUrl: './cards/iron-golem.png',
  },
  {
    definitionId: 'forge_apprentice',
    name: 'Forge Apprentice',
    type: 'unit',
    rarity: 'uncommon',
    cost: 2,
    power: 2,
    keywords: [],
    affinity: ['the_forge'],
    quest: {
      description: 'Play 3 units in a single round.',
      trigger: 'on_unit_played',
      threshold: 3,
      transformsToId: 'master_forger',
    },
    description: 'Quest 3.',
    flavourText: 'Every master was once unsure which end of the hammer to hold.',
    imageUrl: './cards/forge-apprentice.png',
  },
  {
    definitionId: 'master_forger',
    name: 'Master Forger',
    type: 'unit',
    rarity: 'uncommon',
    cost: 2,
    power: 8,
    keywords: ['resilient'],
    affinity: ['the_forge'],
    isTransformTarget: true,
    description: 'Transformed. Resilient.',
    flavourText: 'Three units forged in a single breath. The fires do not care about your limits.',
    imageUrl: './cards/master-forger.png',
  },
  {
    definitionId: 'temper',
    name: 'Temper',
    type: 'spell',
    rarity: 'common',
    cost: 2,
    power: 0,
    keywords: [],
    affinity: ['the_forge'],
    description: 'Give one of your units at The Forge +3 power this round.',
    flavourText: 'Heat reveals the truth in all things.',
    imageUrl: './cards/temper.png',
  },
  // ── Legendaries ──
  {
    definitionId: 'igna_eternal_flame',
    name: 'Igna, Eternal Flame',
    type: 'unit',
    rarity: 'legendary',
    cost: 10,
    power: 7,
    keywords: ['resilient', 'commander'],
    affinity: ['the_forge'],
    quest: {
      description: 'Play 5 units in a single match.',
      trigger: 'on_unit_played',
      threshold: 5,
      transformsToId: 'igna_unchained',
    },
    description: 'Resilient. Commander. Quest 5.',
    flavourText: 'The forge was not built. She was born, and the forge grew around her.',
    imageUrl: './cards/igna-eternal-flame.png',
  },
  {
    definitionId: 'igna_unchained',
    name: 'Igna Unchained',
    type: 'unit',
    rarity: 'legendary',
    cost: 10,
    power: 18,
    keywords: ['overwhelm', 'resilient', 'commander'],
    affinity: ['the_forge'],
    isTransformTarget: true,
    description: 'Transformed. Overwhelm. Resilient. Commander.',
    flavourText: 'Five armies forged in her name. She repaid the debt personally.',
    imageUrl: './cards/igna-unchained.png',
  },
  {
    definitionId: 'ironclad_colossus',
    name: 'Ironclad Colossus',
    type: 'unit',
    rarity: 'legendary',
    cost: 13,
    power: 15,
    keywords: ['overwhelm', 'resilient'],
    affinity: ['the_forge'],
    description: 'Overwhelm. Resilient. An unstoppable engine of war.',
    flavourText: 'It took eleven master smiths and a god\'s blessing to make it walk.',
    imageUrl: './cards/ironclad-colossus.png',
  },
  {
    definitionId: 'forge_wraith',
    name: 'Forge Wraith',
    type: 'unit',
    rarity: 'legendary',
    cost: 10,
    power: 12,
    keywords: ['fleeting', 'overwhelm', 'scorch'],
    affinity: ['the_forge'],
    description: 'Fleeting. Overwhelm. Scorch. On removal, deals its power to opponent\'s strongest unit here.',
    flavourText: 'It burns without fuel. It ends without warning. It leaves nothing behind.',
    imageUrl: './cards/forge-wraith.png',
  },
]

// The Summit affinity — long-game persistence, grinding value across rounds
const SUMMIT_CARDS: CardDefinition[] = [
  {
    definitionId: 'mountain_hermit',
    name: 'Mountain Hermit',
    type: 'unit',
    rarity: 'common',
    cost: 2,
    power: 2,
    keywords: ['resilient'],
    affinity: ['the_summit'],
    description: 'Resilient. Grows stronger the longer it stays.',
    flavourText: 'He left the city fifteen years ago. The mountain kept him.',
    imageUrl: './cards/mountain-hermit.png',
  },
  {
    definitionId: 'ancient_guardian',
    name: 'Ancient Guardian',
    type: 'unit',
    rarity: 'rare',
    cost: 5,
    power: 6,
    keywords: ['resilient', 'elusive'],
    affinity: ['the_summit'],
    description: 'Resilient. Elusive. An immovable force.',
    flavourText: 'It was here before the first war. It will be here after the last.',
    imageUrl: './cards/ancient-guardian.png',
  },
  {
    definitionId: 'frost_sage',
    name: 'Frost Sage',
    type: 'unit',
    rarity: 'uncommon',
    cost: 3,
    power: 2,
    keywords: ['resilient'],
    affinity: ['the_summit'],
    quest: {
      description: 'Survive the start of 2 rounds.',
      trigger: 'on_round_start',
      threshold: 2,
      transformsToId: 'frost_elder',
    },
    description: 'Quest 2.',
    flavourText: 'Patience is the summit\'s only lesson.',
    imageUrl: './cards/frost-sage.png',
  },
  {
    definitionId: 'frost_elder',
    name: 'Frost Elder',
    type: 'unit',
    rarity: 'uncommon',
    cost: 3,
    power: 9,
    keywords: ['resilient', 'elusive'],
    affinity: ['the_summit'],
    isTransformTarget: true,
    description: 'Transformed. Resilient. Elusive.',
    flavourText: 'Two winters survived. The cold no longer speaks to him — it listens.',
    imageUrl: './cards/frost-elder.png',
  },
  // ── Legendaries ──
  {
    definitionId: 'the_unbroken',
    name: 'The Unbroken',
    type: 'unit',
    rarity: 'legendary',
    cost: 11,
    power: 9,
    keywords: ['resilient', 'elusive', 'commander'],
    affinity: ['the_summit'],
    description: 'Resilient. Elusive. Commander. Has never once fallen.',
    flavourText: 'It has no name. Those who faced it did not survive to give it one.',
    imageUrl: './cards/the-unbroken.png',
  },
  {
    definitionId: 'glacier_sovereign',
    name: 'Glacier Sovereign',
    type: 'unit',
    rarity: 'legendary',
    cost: 12,
    power: 14,
    keywords: ['resilient', 'overwhelm'],
    affinity: ['the_summit'],
    description: 'Resilient. Overwhelm. An ancient force that moves like a mountain and hits like a flood.',
    flavourText: 'The glacier does not hurry. It does not need to.',
    imageUrl: './cards/glacier-sovereign.png',
  },
  {
    definitionId: 'summit_prophet',
    name: 'Summit Prophet',
    type: 'unit',
    rarity: 'legendary',
    cost: 8,
    power: 4,
    keywords: ['resilient'],
    affinity: ['the_summit'],
    quest: {
      description: 'Survive the start of 3 rounds.',
      trigger: 'on_round_start',
      threshold: 3,
      transformsToId: 'ascended_prophet',
    },
    description: 'Resilient. Quest 3.',
    flavourText: 'She climbed the mountain to find answers. The mountain gave her something better.',
    imageUrl: './cards/summit-prophet.png',
  },
  {
    definitionId: 'ascended_prophet',
    name: 'Ascended Prophet',
    type: 'unit',
    rarity: 'legendary',
    cost: 8,
    power: 16,
    keywords: ['resilient', 'elusive', 'commander'],
    affinity: ['the_summit'],
    isTransformTarget: true,
    description: 'Transformed. Resilient. Elusive. Commander.',
    flavourText: 'Three winters endured. The summit answered.',
    imageUrl: './cards/ascended-prophet.png',
  },
]

// The Rift affinity — burst tempo, huge single-round power spikes
const RIFT_CARDS: CardDefinition[] = [
  {
    definitionId: 'spark_sprite',
    name: 'Spark Sprite',
    type: 'unit',
    rarity: 'common',
    cost: 1,
    power: 3,
    keywords: ['fleeting'],
    affinity: ['the_rift'],
    description: 'Fleeting. High burst, gone next round.',
    flavourText: 'Blink and it\'s gone. Hesitate and so are you.',
    imageUrl: './cards/spark-sprite.png',
  },
  {
    definitionId: 'chaos_drake',
    name: 'Chaos Drake',
    type: 'unit',
    rarity: 'rare',
    cost: 4,
    power: 6,
    keywords: ['fleeting', 'overwhelm'],
    affinity: ['the_rift'],
    description: 'Fleeting. Overwhelm.',
    flavourText: 'It doesn\'t aim. It doesn\'t need to.',
    imageUrl: './cards/chaos-drake.png',
  },
  {
    definitionId: 'phase_walk',
    name: 'Phase Walk',
    type: 'spell',
    rarity: 'uncommon',
    cost: 2,
    power: 0,
    keywords: [],
    affinity: ['the_rift'],
    description: 'Move one of your units to a different location.',
    flavourText: 'Between one heartbeat and the next, everything changes.',
    imageUrl: './cards/phase-walk.png',
  },
  {
    definitionId: 'rift_caller',
    name: 'Rift Caller',
    type: 'unit',
    rarity: 'uncommon',
    cost: 3,
    power: 3,
    keywords: [],
    affinity: ['the_rift'],
    quest: {
      description: 'Have 3 Fleeting cards leave the board.',
      trigger: 'on_unit_played',
      threshold: 3,
      transformsToId: 'rift_herald',
    },
    description: 'Quest 3.',
    flavourText: 'He opens the door. He does not ask what comes through.',
    imageUrl: './cards/rift-caller.png',
  },
  {
    definitionId: 'rift_herald',
    name: 'Rift Herald',
    type: 'unit',
    rarity: 'uncommon',
    cost: 3,
    power: 10,
    keywords: ['fleeting', 'overwhelm'],
    affinity: ['the_rift'],
    isTransformTarget: true,
    description: 'Transformed. Fleeting. Overwhelm.',
    flavourText: 'The rift tore three worlds apart. He wore the mark of all of them.',
    imageUrl: './cards/rift-herald.png',
  },
  // ── Legendaries ──
  {
    definitionId: 'void_leviathan',
    name: 'Void Leviathan',
    type: 'unit',
    rarity: 'legendary',
    cost: 10,
    power: 17,
    keywords: ['fleeting', 'overwhelm', 'scorch'],
    affinity: ['the_rift'],
    description: 'Fleeting. Overwhelm. Scorch. A catastrophic burst threat that leaves nothing standing.',
    flavourText: 'It doesn\'t cross the rift. It is the rift.',
    imageUrl: './cards/void-leviathan.png',
  },
  {
    definitionId: 'rift_sovereign',
    name: 'Rift Sovereign',
    type: 'unit',
    rarity: 'legendary',
    cost: 9,
    power: 8,
    keywords: ['commander', 'overwhelm'],
    affinity: ['the_rift'],
    description: 'Commander. Overwhelm. While in play, friendly Fleeting cards here gain +3 power.',
    flavourText: 'Order from chaos. He commands the storm without flinching.',
    imageUrl: './cards/rift-sovereign.png',
  },
  {
    definitionId: 'entropic_maw',
    name: 'Entropic Maw',
    type: 'unit',
    rarity: 'legendary',
    cost: 11,
    power: 13,
    keywords: ['fleeting', 'overwhelm'],
    affinity: ['the_rift'],
    description: 'Fleeting. Overwhelm. On play, move your weakest unit here to any other location.',
    flavourText: 'It does not hunger. It simply unravels everything it touches.',
    imageUrl: './cards/entropic-maw.png',
  },
]

// The Graveyard affinity — recursion, death synergies
const GRAVEYARD_CARDS: CardDefinition[] = [
  {
    definitionId: 'bone_knight',
    name: 'Bone Knight',
    type: 'unit',
    rarity: 'common',
    cost: 2,
    power: 3,
    keywords: ['fleeting'],
    affinity: ['the_graveyard'],
    description: 'Fleeting. Returns to hand from The Graveyard.',
    flavourText: 'Death is just a detour when you know the way home.',
    imageUrl: './cards/bone-knight.png',
  },
  {
    definitionId: 'revenant',
    name: 'Revenant',
    type: 'unit',
    rarity: 'uncommon',
    cost: 3,
    power: 4,
    keywords: ['fleeting'],
    affinity: ['the_graveyard'],
    description: 'Fleeting. Pairs with Graveyard\'s recursion effect.',
    flavourText: 'It remembers the name of every person who thought it was gone for good.',
    imageUrl: './cards/revenant.png',
  },
  {
    definitionId: 'soul_collector',
    name: 'Soul Collector',
    type: 'unit',
    rarity: 'rare',
    cost: 4,
    power: 4,
    keywords: [],
    affinity: ['the_graveyard'],
    quest: {
      description: 'Have 3 Fleeting units leave the board.',
      trigger: 'on_unit_played',
      threshold: 3,
      transformsToId: 'death_reaper',
    },
    description: 'Quest 3.',
    flavourText: 'Three souls. It only needed three.',
    imageUrl: './cards/soul-collector.png',
  },
  {
    definitionId: 'death_reaper',
    name: 'Death Reaper',
    type: 'unit',
    rarity: 'rare',
    cost: 4,
    power: 10,
    keywords: ['elusive'],
    affinity: ['the_graveyard'],
    isTransformTarget: true,
    description: 'Transformed. Elusive.',
    flavourText: 'You cannot bargain with what you do not understand.',
    imageUrl: './cards/death-reaper.png',
  },
  // ── Legendaries ──
  {
    definitionId: 'lord_of_bones',
    name: 'Lord of Bones',
    type: 'unit',
    rarity: 'legendary',
    cost: 12,
    power: 11,
    keywords: ['resilient', 'commander'],
    affinity: ['the_graveyard'],
    description: 'Resilient. Commander. Friendly Fleeting units here gain +2 power.',
    flavourText: 'They offered him a throne. He built one himself — out of what remained.',
    imageUrl: './cards/lord-of-bones.png',
  },
  {
    definitionId: 'the_undying',
    name: 'The Undying',
    type: 'unit',
    rarity: 'legendary',
    cost: 11,
    power: 10,
    keywords: ['resilient', 'elusive'],
    affinity: ['the_graveyard'],
    description: 'Resilient. Elusive. Every death makes it stronger.',
    flavourText: 'They killed it four times. After the fourth, they stopped trying.',
    imageUrl: './cards/the-undying.png',
  },
  {
    definitionId: 'banshee_queen',
    name: 'Banshee Queen',
    type: 'unit',
    rarity: 'legendary',
    cost: 9,
    power: 6,
    keywords: ['elusive'],
    affinity: ['the_graveyard'],
    quest: {
      description: 'Have 4 Fleeting units leave the board.',
      trigger: 'on_unit_played',
      threshold: 4,
      transformsToId: 'death_incarnate',
    },
    description: 'Elusive. Quest 4.',
    flavourText: 'She wept for the dying. Then she stopped weeping and started working.',
    imageUrl: './cards/banshee-queen.png',
  },
  {
    definitionId: 'death_incarnate',
    name: 'Death Incarnate',
    type: 'unit',
    rarity: 'legendary',
    cost: 9,
    power: 16,
    keywords: ['elusive', 'overwhelm'],
    affinity: ['the_graveyard'],
    isTransformTarget: true,
    description: 'Transformed. Elusive. Overwhelm.',
    flavourText: 'Four taken. The debt is now the world\'s problem.',
    imageUrl: './cards/death-incarnate.png',
  },
]

// The Sanctum affinity — spell synergies, combo/quest payoffs
const SANCTUM_CARDS: CardDefinition[] = [
  {
    definitionId: 'ritual_caster',
    name: 'Ritual Caster',
    type: 'unit',
    rarity: 'common',
    cost: 2,
    power: 2,
    keywords: [],
    affinity: ['the_sanctum'],
    description: 'A practiced magic user.',
    flavourText: 'The words matter. The will matters more.',
    imageUrl: './cards/ritual-caster.png',
  },
  {
    definitionId: 'mana_surge',
    name: 'Mana Surge',
    type: 'spell',
    rarity: 'common',
    cost: 1,
    power: 0,
    keywords: [],
    affinity: ['the_sanctum'],
    description: 'Draw 1 card.',
    flavourText: 'A single spark, drawn at the right moment, is enough.',
    imageUrl: './cards/mana-surge.png',
  },
  {
    definitionId: 'apprentice_mage',
    name: 'Apprentice Mage',
    type: 'unit',
    rarity: 'uncommon',
    cost: 2,
    power: 1,
    keywords: [],
    affinity: ['the_sanctum'],
    quest: {
      description: 'Play 3 spells.',
      trigger: 'on_spell_played',
      threshold: 3,
      transformsToId: 'archmage',
    },
    description: 'Quest 3.',
    flavourText: 'She memorised three hundred spells before she cast her first.',
    imageUrl: './cards/apprentice-mage.png',
  },
  {
    definitionId: 'archmage',
    name: 'Archmage',
    type: 'unit',
    rarity: 'uncommon',
    cost: 2,
    power: 9,
    keywords: ['elusive'],
    affinity: ['the_sanctum'],
    isTransformTarget: true,
    description: 'Transformed. Elusive.',
    flavourText: 'Three spells. That was all it took to cross the boundary between knowledge and mastery.',
    imageUrl: './cards/archmage.png',
  },
  {
    definitionId: 'arcane_echo',
    name: 'Arcane Echo',
    type: 'spell',
    rarity: 'rare',
    cost: 3,
    power: 0,
    keywords: [],
    affinity: ['the_sanctum'],
    description: 'Copy the last spell played this round.',
    flavourText: 'The second time is always cheaper.',
    imageUrl: './cards/arcane-echo.png',
  },
  // ── Legendaries ──
  {
    definitionId: 'the_archon',
    name: 'The Archon',
    type: 'unit',
    rarity: 'legendary',
    cost: 11,
    power: 8,
    keywords: ['elusive', 'commander'],
    affinity: ['the_sanctum'],
    description: 'Elusive. Commander. Your spells this round give +2 extra power.',
    flavourText: 'He did not learn magic. He became it.',
    imageUrl: './cards/the-archon.png',
  },
  {
    definitionId: 'living_codex',
    name: 'Living Codex',
    type: 'unit',
    rarity: 'legendary',
    cost: 10,
    power: 5,
    keywords: ['resilient'],
    affinity: ['the_sanctum'],
    quest: {
      description: 'Play 5 spells.',
      trigger: 'on_spell_played',
      threshold: 5,
      transformsToId: 'codex_of_ages',
    },
    description: 'Resilient. Quest 5.',
    flavourText: 'It writes itself. That is the part that concerns everyone.',
    imageUrl: './cards/living-codex.png',
  },
  {
    definitionId: 'codex_of_ages',
    name: 'Codex of Ages',
    type: 'unit',
    rarity: 'legendary',
    cost: 10,
    power: 16,
    keywords: ['resilient', 'elusive'],
    affinity: ['the_sanctum'],
    isTransformTarget: true,
    description: 'Transformed. Resilient. Elusive.',
    flavourText: 'Five spells cast. The last word written. The book closed — and then opened again.',
    imageUrl: './cards/codex-of-ages.png',
  },
  {
    definitionId: 'grand_invocation',
    name: 'Grand Invocation',
    type: 'spell',
    rarity: 'legendary',
    cost: 8,
    power: 0,
    keywords: [],
    affinity: ['the_sanctum'],
    description: 'Draw 3 cards.',
    flavourText: 'The words take a lifetime to learn. The effect takes less than a second.',
    imageUrl: './cards/grand-invocation.png',
  },
]

export const CARD_DATABASE: CardDefinition[] = [
  ...NEUTRAL_CARDS,
  ...FORGE_CARDS,
  ...SUMMIT_CARDS,
  ...RIFT_CARDS,
  ...GRAVEYARD_CARDS,
  ...SANCTUM_CARDS,
]
