import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { execFileSync } from 'node:child_process'

// Preserve generated originals and encode full-resolution copies for the game.
const root = 'output/shattered-pacts-art'
const destination = 'apps/web/public/cards/shattered-pacts'
const { entries } = JSON.parse(readFileSync(`${root}/prompts.json`, 'utf8')) as {
  entries: { id: string; source?: string }[]
}
mkdirSync(`${root}/originals`, { recursive: true })
mkdirSync(destination, { recursive: true })
const art: Record<string, string> = {}
for (const { id, source } of entries) {
  if (!/^[a-z_]+$/.test(id)) throw new Error(`Invalid card id: ${id}`)
  const original = `${root}/originals/${id}.png`
  if (!existsSync(original)) {
    if (!source || !existsSync(source)) continue
    copyFileSync(source, original)
  }
  const output = `${destination}/${id}.webp`
  if (!existsSync(output)) execFileSync('cwebp', ['-quiet', '-q', '88', '-m', '6', original, '-o', output])
  art[id] = `./cards/shattered-pacts/${id}.webp`
}
writeFileSync('packages/shared/src/constants/arenaArt.ts',
  '// Generated by scripts/install-arena-art.ts from completed, reviewed illustrations.\n' +
  `export const ARENA_EXPANSION_ART: Partial<Record<string, string>> = ${JSON.stringify(art, null, 2)}\n`)
console.log(`Installed ${Object.keys(art).length} original card illustrations.`)
